### ISSUE TITLE
Error: Cannot initialize VectorStoreIndex without nodes or indexStruct

### ISSUE THREAD

**Issue by nstylianides** [run-llama/create-llama#331] opened 2024-09-27 13:51 UTC
using latest create llamaindex project with next.js
using pdf in data folder. 
We run npm run generate but index_store.json is not created. 
We then try to run npm run dev and once we try a chat we get this error.

**Comment by leehuwuj** [comment] 2024-10-01 02:46
Hi @nstylianides what are your other options when creating llama app? I had a try on NextJS template but could not reproduce you issue:
```
❯ npx create-llama@latest
✔ What is your project named? … my-app
✔ Which template would you like to use? › Agentic RAG (e.g. chat with docs)
✔ Which framework would you like to use? › NextJS
✔ Would you like to set up observability? › No
✔ Please provide your OpenAI API key (leave blank to skip): …
✔ Which data source would you like to use? › Use an example PDF
✔ Would you like to add another data source? › No
✔ Would you like to use LlamaParse (improved parser for RAG - requires API key)? … no / yes
✔ Would you like to use a vector database? › No, just store the data in the file system
✔ Would you like to build an agent using tools? If so, select the tools here, otherwise just press enter ›
✔ How would you like to proceed? › Generate code, install dependencies, and run the app (~2 min)
```

If you don't have `index_store.json` in the cache folder then i guess you had chosen the `No data source` option. Please make sure you had a file in the data folder.

**Comment by nstylianides** [comment] 2024-10-02 05:21
Hi there. I have resolved the issue by using WSL env in my windows.

When using llamaindex index in windows i have concluded to the following: 

1. Python example in Windows it works. 
2. LlamaIndex.ts in windows it always fails to create the index_store.json
3. LlamaIndex.ts in windows WSL it works like a charm. 

I am not sure what is the issue since error reporting is either missing or confusing. e.g. "contextWindow" could be easily confused with browser context windows. 

THANK YOU FOR THIS LIBRARY for it can be a swiss knife in every dev toolset. 
But, IMHO, it needs much better documentation, reference and howto based on cases. 

Is there an official Course on how to better utilize the Llmaindex library?

**Comment by marcusschiesser** [comment] 2024-12-19 05:01
closing this as we're running a e2e test using windows with LlamaIndex.ts. @nstylianides fill free to reopen with a reproducible test case

**Closed by marcusschiesser** 2024-12-19 05:01 UTC
